spring.application.name=hshop-api

spring.r2dbc.url=jdbc:postgresql://localhost:5432/hshop_db
spring.r2dbc.username=hshop_user
spring.r2dbc.password=hshop_password
spring.r2dbc.properties.schema=hshop

spring.sql.init.mode=always